export default {
  "date": {
    "now": "Just now",
    "hoursAgo": "{hours}h ago",
    "yesterday": "Yesterday",
    "daysAgo": "{days} days ago"
  },
  nav: {
    home: 'Home',
    board: 'Board',
    myBoards: 'My Boards',
    features: 'Features',
    pricing: 'Pricing',
    testimonials: 'Testimonials',
    login: 'Login',
    signUp: 'Sign Up Free'
  },
  boardStatistics: {
    totalColumns: 'Total Columns',
    totalCards: 'Total Cards',
    totalLabels: 'Total Labels',
    totalLikes: 'Total Likes',
    totalDislikes: 'Total Dislikes',
    totalComments: 'Total Comments',
    boardSummary: 'Board Summary',
    boardSummaryRegenerateButton: 'Generate',
    boardSummaryAIText: 'Generated by AI based on board activity and content',
    teamMembers: 'Board Members',
    labelsDistribution: 'Labels Distribution',
    engagementMetrics: 'Engagement Metrics',
    commentsPerCard: 'Comments per Card',
    labelsPerCards: 'Labels per Card',
    notSupportTitle: 'Sorry',
    notSupport: 'This board does not support statistics.'
  },
  myBoards: {
    title: 'My Boards',
    titleParticipate: 'Boards I participate in',
    createBoard: 'Create New Board',
    members: 'members',
    columns: 'columns',
    items: 'items',
    search: {
      placeholder: 'Search boards...',
      clear: 'Clear search',
      results: 'Showing {count} of {total} boards for "{query}"',
      showAll: 'Show All Boards',
      noResults: 'No boards found',
      noResultsDesc: 'No boards match your search for "{query}". Try a different search term.'
    },
    emptyState: {
      title: 'No boards yet',
      description: 'Create your first board to start organizing your projects.',
      cta: 'Create Your First Board'
    },
    actions: {
      view: 'View Board',
      delete: 'Delete Board',
      statistics: 'Board Statistics'
    },
    deleteModal: {
      title: 'Delete Board',
      message: 'Are you sure you want to delete "{board}"? This action cannot be undone.',
      cancel: 'Cancel',
      confirm: 'Delete Board'
    }
  },
  auth: {
    googleLogin: 'Continue with Google',
    or: 'or',
    myProfile: 'My Profile',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    startJourney: 'Start your journey with us',
    enterEmail: 'Enter your email to receive a verification code',
    email: 'Email address',
    fullName: 'Full name',
    continue: 'Continue',
    verify: 'Verify',
    newUser: 'New user?',
    signUp: 'Sign up',
    signIn: 'Sign in',
    alreadyHaveAccount: 'Do You is already have account, please proceed to login.',
    otpSent: 'We sent a verification code to',
    resendCode: 'Resend code',
    resendIn: 'Resend code in',
    changeEmail: 'Change email',
    invalidOTP: 'Invalid verification code',
    verificationSuccess: 'Verification successful',
    phone: 'Phone number',
    invalidPhone: 'Please enter a valid phone number',
    logout: 'Logout',
  },
  hero: {
    myBoard: 'My Board',
    new: "New: Integrated AI for maximum productivity",
    title: 'Visualize Your Workflow with',
    subtitle: 'Visible work, incredible results. Simplify your management with our Kanban board.',
    getStarted: 'Get Started',
    watchDemo: 'Watch Demo',
    subtitle_footer: 'Is a web modern board, open-source application based in columns and cards.',
    textVariations: [
      "Visualize your Workflow with",
      "Organize your Tasks with",
      "Manage your Projects with",
      "Collaborate with your Team using",
      "Boost your Productivity with"
    ]
  },
  features: {
    title: "Features that make your workflow smoother",
    subtitle: "Everything you need to manage projects effectively and boost productivity",
    coming: "Coming soon",
    taskManagement: {
      title: "Retrospective Management",
      description: "Customize and manage retrospectives intuitively to optimize team collaboration."
    },
    teamCollaboration: {
      title: "Team Collaboration",
      description: "Work together with real-time board updates."
    },
    customization: {
      title: "Customizable Boards",
      description: "Create personalized workflows that fit your team’s unique processes."
    },
    analytics: {
      title: 'Board Analysis',
      description: 'Get insights into everything that happened with your boards in a simple and objective way.'
    },
    voting: {
      title: "Voting & Prioritization",
      description: "Allow the team to vote on the most important topics to focus on what truly matters."
    },
    anonymous: {
      title: "Anonymous Mode",
      description: "Give your team more freedom by enabling honest feedback without pressure."
    },
    ai: {
      title: 'Artificial Intelligence',
      description: 'With the help of our AI, your workflow on the boards becomes more productive.'
    },
  },
  "pricing": {
    "title": "Simple and Transparent Pricing",
    "subtitle": "No hidden fees, no surprises. Choose the plan that works for you.",
    "free": {
      "name": "Free",
      "description": "The perfect plan",
      "price": "R$0",
      "period": " always free",
      "button": "Get Started Now",
      "feat1": "Unlimited Boards",
      "feat2": "Unlimited Team Members"
    },
    "features": {
      "unlimited": "Unlimited Boards",
      "teamMembers": "Up to {count} team members",
      "unlimitedMembers": "Unlimited Members",
      "boardSummaryAi": "Summary board with AI",
      "unlimitedTemplates": "Access full templates"
    }
  },
  testimonials: {
    title: 'What our customers say',
    subtitle: 'Trusted by thousands of teams worldwide'
  },
  cta: {
    title: 'Ready to transform your workflow?',
    subtitle: 'Identify challenges, align expectations and constantly evolve.',
    button: 'Get Started for Free'
  },
  cookies: {
    message: 'We use cookies to enhance your experience. By continuing to visit this site, you agree to our use of cookies.',
    privacyPolicy: 'Privacy Policy',
    accept: 'Accept',
    reject: 'Reject'
  },
  board: {
    title: 'Kanban Board',
    addColumn: 'Add Column',
    resetBoard: 'Reset Board',
    newColumn: 'New Column',
    deleteColumn: 'Delete Column',
    deleteColumnConfirm: 'Are you sure you want to delete this column and all its cards?',
    addCard: 'Add Card',
    editCard: 'Edit Card',
    deleteCard: 'Delete Card',
    deleteCardConfirm: 'Are you sure you want to delete this card?',
    cardTitle: 'Title',
    cardDescription: 'Description',
    cardLabels: 'Labels',
    save: 'Save',
    cancel: 'Cancel',
    filter: 'Filter',
    filterAll: 'All Cards',
    filterLiked: 'Liked Cards',
    filterDisliked: 'Disliked Cards',
    filterMostLiked: 'Most Liked',
    filterMostDisliked: 'Most Disliked',
    settings: 'Board Settings',
    settingsTheme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    settingsShowLike: 'Show Likes',
    settingsShowVisibility: 'Show Visibility',
    settingsShowAuthorCard: 'Show Author Card',
    settingsShowTitle: 'Show Title',
    settingsShowDescription: 'Show Description',
    settingsShowTags: 'Show Labels',
    emptyState: {
      title: "Time to get started",
      description: "Start by creating the columns for your board",
      cta: "Create First Column"
    },
    aiAssist: {
      title: "AI Assist",
      chatInputLabel: "Ask me anything about yout board...",
      quickQuestionsText: "Quick Questions",
      justNow: "Just now",
      "greeting": "👋 Hello! My name is Kira I'm your AI assistant for this Kanban board.",
      "helpIntro": "I can help you with:",
      "items": {
        "progress": "Analyzing your board progress",
        "suggestions": "Suggesting improvements",
        "questions": "Answering questions about tasks",
        "tips": "Providing productivity tips"
      },
      "questions": {
        "boardProgress": {
          "label": "Board Progress",
          "message": "How is my board progressing?"
        },
        "bottlenecks": {
          "label": "Bottlenecks",
          "message": "Are there any bottlenecks in my workflow?"
        },
        "suggestions": {
          "label": "Suggestions",
          "message": "What improvements do you suggest?"
        },
        "teamPerformance": {
          "label": "Team Performance",
          "message": "How is my team performing?"
        },
        "boardSummary": {
          "label": "Board Summary",
          "message": "Could you generate an overall summary of my board?"
        }
      }
    }
  },
  demo: {
    alert: "This is a demo environment. All data will be deleted in 30 minutes. Create a free account to access all features."
  }
  ,
  footer: {
    boards: {
      title: "Boards",
      link1:
        "My Boards",
      link2:
        "New Board"
    }
    ,
    terms: {
      title: 'Terms',
      link1:
        'Privacy Policy',
      link2:
        'Terms of Use',
    }
    ,
    account: {
      title: "Account",
      link1:
        "Login",
      link2:
        "Create Account"
    }
    ,
    status: {
      title: "Status/Help",
      link1:
        "Having an issue?",
      link2:
        "API Status"
    }
    ,
    "copyright":
      "© 2025 KanbanFlex.",
  }
  ,
  language: {
    en: 'English',
    'pt-BR':
      'Português (BR)'
  }
  ,
  templates: {
    name: 'Template',
    chooseStart:
      'Choose how to start',
    blankBoard:
      {
        title: 'Start from Scratch',
        description:
          'Create a blank board and customize it to your needs'
      }
    ,
    useTemplate: {
      title: 'Use a Template',
      description:
        'Choose from our pre-built templates to get started quickly'
    }
    ,
    popularTemplates: 'Popular Templates',
    types:
      {
        blankBoard: {
          name: 'Board Title',
          description:
            'Board empty'
        }
        ,
        sprintRetrospective: {
          name: 'Sprint Retrospective',
          description:
            'Plan and execute sprint retrospectives',
          columns:
            {
              first: 'What went well',
              second:
                'To improve',
              third:
                'Action Items / To do next',
            }
        }
        ,
        projectManagement: {
          name: 'Project Management',
          description:
            'Track tasks, milestones, and team progress',
          columns:
            {
              first: 'Backlog',
              second:
                'To Do',
              third:
                'In Progress',
              fourth:
                'Review',
              fifth:
                'Done',
            }
        }
        ,
        developmentSprint: {
          name: 'Development Sprint',
          description:
            'Manage software development sprints',
          columns:
            {
              first: 'Sprint Backlog',
              second:
                'In Development',
              third:
                'Code Review',
              fourth:
                'QA Testing',
              fifth:
                'Done',
            }
        }
        ,
        okrTracking: {
          name: 'OKR Tracking',
          description:
            'Track objectives and key results',
          columns:
            {
              first: 'Objectives',
              second:
                'Key Results',
              third:
                'Initiatives',
              fourth:
                'Completed',
            }
        }
        ,
        contentCalendar: {
          name: 'Content Calendar',
          description:
            'Plan and schedule content creation',
          columns:
            {
              first: 'Content Ideas',
              second:
                'Writing',
              third:
                'Editing',
              fourth:
                'Review',
              fifth:
                'Published',
            }
        }
        ,
        bugTracking: {
          name: 'Bug Tracking',
          description:
            'Track and manage software issues',
          columns:
            {
              first: 'Reported',
              second:
                'To Reproduce',
              third:
                'In Progress',
              fourth:
                'Testing',
              fifth:
                'Fixed',
            }
        }
        ,
        productLaunch: {
          name: 'Product Launch',
          description:
            'Plan and execute product launches',
          columns:
            {
              first: 'Planning',
              second:
                'In Progress',
              third:
                'Review',
              fourth:
                'Approved',
              fifth:
                'Launched',
            }
        }
        ,
        demo: {
          name: 'My Article Publications',
          card1:
            {
              title: 'Article on Industry Trends',
              description:
                '👨‍💻 Write an article about industry trends',
              labels:
                'Trends, Blog, Study'
            }
          ,
          card2: {
            title: 'Article on WEB3 Trends',
            description:
              'Write an article about WEB3 trends',
            labels:
              'Research, Blog, WEB3'
          }
          ,
          card3: {
            title: 'Article on Computer Vision',
            description:
              'Write an article about computer vision',
            labels:
              'Research, Blog, Study'
          }
          ,
          card4: {
            title: 'Article on AI',
            description:
              'Write an article about artificial intelligence',
            labels:
              'Research, Blog, Study, AI'
          }
        }

      }
  }
  ,
  myProfile: {
    accessLogs: 'Access Logs',
    profile:
      'My Profile',
    myPlan: 'My Plan',
    register:
      'Register',
    login:
      'Login',
    accept:
      'I agree to the use of my data as per',
    success:
      'Success',
    save:
      'Save with success.',
    error:
      'Error to save.',
    saveProfile:
      'Save with success',
    errorSaveProfile:
      'Error to save.',
    confirmDelete:
      'Delete Account',
    deleteWarning:
      'Are you sure you want to delete your account? This will deactivate your account and you will no longer be able to access the system.',
    deleteIrreversible:
      'This action cannot be undone!',
    cancel:
      'Cancel',
    confirmDeleteBtn:
      'Delete Account',
    accountDeactivated:
      'Your account has been deactivated successfully.',
    errorDeactivating:
      'Error deactivating your account. Please try again.',
    freePlan: 'Free Plan',
    freePlanDescription: 'Basic plan with limited features',
    storageUsage: 'Storage Usage',
    storageRemaining: 'Remaining:',
    planFeatures: 'Plan Features',
    feature1: '1GB storage',
    feature2: 'Basic access to resources',
    feature3: 'Email support',
    upgradePlan: 'Upgrade Plan',
    upgradeDescription: 'Get more space and features with our premium plans.',
    comingSoon: 'Coming Soon',
    manageFiles: 'Manage Files',
    viewAllFiles: 'View All Files',
    manageFilesDescription: 'View, download or remove your uploaded files'
  }
  ,
  myAttachments: {
    title: 'My Files',
    backToProfile: 'Back to Profile',
    fileName: 'File Name',
    fileType: 'Type',
    fileSize: 'Size',
    uploadDate: 'Upload Date',
    actions: 'Actions',
    storageUsed: 'Storage Used',
    attachedToBoard: 'Attached to board',
    downloadStarted: 'Download started',
    deleteSuccess: 'File removed successfully',
    search: {
      placeholder: 'Search files...',
      noResults: 'No files found',
      noResultsDesc: 'No files match your search for "{query}". Try a different search term.',
      showAll: 'Show All Files',
      results: 'Showing {count} file(s) for "{query}"'
    },
    emptyState: {
      title: 'No files yet',
      description: 'You haven\'t uploaded any files yet. Files uploaded in boards will appear here.'
    },
    deleteModal: {
      title: 'Remove File',
      message: 'Are you sure you want to remove "{fileName}"?',
      warning: 'This action cannot be undone!',
      cancel: 'Cancel',
      confirm: 'Remove File'
    },
    errors: {
      loadFailed: 'Error loading files',
      searchFailed: 'Error searching files',
      downloadFailed: 'Error downloading file',
      deleteFailed: 'Error removing file'
    }
  }
  ,
  boardV2: {
    statistics: 'Statistics',
    newCard: 'New Card',
    newCardDescription: 'Create a new card for you board',
    editCardDescription: 'Update your card information',
    title: 'Title',
    titlePlaceholder: 'Enter card title...',
    description: 'Description',
    descriptionPlaceholder: 'Describe the card details...',
    labels: 'Tags',
    labelsPlaceholder: 'Type a tag and press Enter...',
    close: 'Close',
    save: 'Save',
    identify: 'Identify Yourself',
    name: 'Name',
    email: 'Email',
    enterAsAnonymous: 'Enter as Anonymous',
    editBoardName: 'Edit board name',
    boardName: 'Board name',
    newColumn: 'New column',
    columnName: 'Column name',
    editColumn: 'Edit column',
    editCard: 'Edit card',
    comments: 'Comments',
    noComments: 'No comments yet.',
    delete: 'Delete',
    writeComment: 'Write a comment...',
    addComment: 'Add Comment',
    cardHideText: 'Hold on, curious one! The card content is hidden. And remember, curiosity killed the cat.',
    priority: 'Priority',
    selectPriority: 'Select priority',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    dueDate: 'Due Date',
    assignedMembers: 'Assigned Members',
    searchMembers: 'Search members...',
    attachments: 'Attachments',
    attachment: 'Attachment',
    noAttachments: 'No attachments yet',
    dragFilesHere: 'Drag files here or click to select',
    selectFiles: 'Select Files',
    activity: 'Activity',
    noActivity: 'No activity recorded',
    createdCard: 'Created the card.',
    movedCard: 'Moved the card from "{source}" to "{target}"',
    addItemPlaceholder: 'Add item...',
    progress: 'Progress',
    noChecklistItems: 'No items in the list',
    checklist: 'Checklist',
    details: 'Details',
    createdOn: 'Created on',
    lastUpdate: 'Last update',
    createdBy: 'Created by',
    cardId: 'Card ID',
    deleteCard: 'Delete Card',
    cancel: 'Cancel',
    createCard: 'Create Card',
    errors:
      {
        oops: 'Oops...',
        nameRequired:
          'You need to provide your name!',
        emailRequired:
          'You need to provide a valid email!',
        titleRequired:
          'You need to provide the card title!',
        columnNameRequired:
          'You need to provide the column name!',
        descriptionRequired: 'You need to provide the card description!',
        uploadOnlyInEdit: 'Uploads are only available when editing an existing card',
      },
    confirmations: {
      removeCard: 'Are you sure you want to remove this card?',
      removeColumn: 'Are you sure you want to remove this column?',
      removeAttachment: 'Are you sure you want to remove this attachment?',
      yes: 'Yes',
      no: 'No'
    },
    notifications: {
      alreadyLiked: 'You already liked this card!',
      alreadyDisliked:
        'You already disliked this card!',
      failedToUpdateVote:
        'Failed to update vote',
      errorUpdatingVote:
        'Error updating vote',
      failedToUpdateCard:
        'Failed to update card',
      cardUpdatedSuccess:
        'Card updated successfully!',
      errorUpdatingCard:
        'Error updating card',
      boardVisibilityFailed:
        'Failed to update board visibility',
      boardNowVisible:
        'Board is now visible!',
      boardNowHidden:
        'Board is now hidden!',
      errorUpdatingVisibility:
        'Error updating board visibility',
      failedToRemoveCard:
        'Failed to remove card',
      cardRemovedSuccess:
        'Card removed successfully!',
      errorRemovingCard:
        'Error removing card',
      failedToRemoveColumn:
        'Failed to remove column',
      columnRemovedSuccess:
        'Column removed successfully!',
      errorRemovingColumn:
        'Error removing column',
      failedToUpdateColumn:
        'Failed to update column',
      columnUpdatedSuccess:
        'Column updated successfully!',
      errorUpdatingColumn:
        'Error updating column',
      failedToAddColumn:
        'Failed to add column',
      columnAddedSuccess:
        'Column added successfully!',
      errorAddingColumn:
        'Error adding column',
      failedToAddCard:
        'Failed to add card',
      cardAddedSuccess:
        'Card added successfully!',
      errorAddingCard:
        'Error adding card',
      failedToReorderColumns:
        'Failed to reorder columns',
      columnsReorderedSuccess:
        'Columns reordered successfully!',
      errorReorderingColumns:
        'Error reordering columns',
      failedToReorderCards:
        'Failed to reorder cards',
      cardsReorderedSuccess:
        'Cards reordered successfully!',
      errorReorderingCards:
        'Error reordering cards',
      failedToMoveCard:
        'Failed to move card',
      cardMovedSuccess:
        'Card moved successfully!',
      errorMovingCard:
        'Error moving card',
      failedToAddComment:
        'Failed to add comment',
      commentAddedSuccess:
        'Comment added successfully!',
      errorAddingComment:
        'Error adding comment',
      failedToRemoveComment:
        'Failed to remove comment',
      commentRemovedSuccess:
        'Comment removed successfully!',
      errorRemovingComment:
        'Error removing comment'
    }
  }
  ,
  createBoard: {
    success: 'Board created successfully!',
    error:
      {
        title: 'Oops...',
        message:
          'An error occurred while creating the board!'
      }
  }
  ,
  error: {
    notFound: 'Board or page not found.',
    back:
      'Back'
  }
};
